version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting Backup Process..."
      - apt update && apt install zip -y  # Install zip utility for Ubuntu
  build:
    commands:
      - echo "Zipping the current build..."
      - zip -r old_version.zip *          # Zip the current directory
      - echo "Uploading ZIP to S3..."
      - aws s3 cp old_version.zip s3://s3-for-store-zip /$(date +%Y%m%d%H%M%S)_old_version.zip
  post_build:
    commands:
      - echo "Backup Completed."

artifacts:
  files:
    - '**/*'
